version: "3.9"

services:
  api:
    build: .
    container_name: prod_ready_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - app_net

  mysql:
    image: mysql:8
    container_name: prod_ready_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prod_ready_api
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_net

  redis:
    image: redis:7
    container_name: prod_ready_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_net

volumes:
  mysql_data:

networks:
  app_net:
